#include "pgm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>

#define PGM_MAXVAL 255

int pgm_write(const char *filename, const uint8_t *data, int width, int height)
{
    FILE *file = fopen(filename, "wb"); // write binary
    if (file == NULL) return -1;

    fprintf(file, "P5\n# generated by gol\n%d %d\n%d\n", width, height, PGM_MAXVAL);

    size_t image_size = (size_t)width * (size_t)height;
    if (fwrite(data, sizeof(uint8_t), image_size, file) != image_size) {
        fclose(file);
        return -2;
    }

    fclose(file);
    return 0;
}

int pgm_read(const char *filename, uint8_t **data, int *width, int *height)
{
    FILE *file = fopen(filename, "rb"); // read binary
    if (file == NULL) return -1;

    char magic[3]; // counts terminal '\0'
    int maxval;
    char line[256];

    if (fscanf(file, "%2s", magic) != 1) {
        fclose(file);
        return -2;
    }

    fgetc(file); // consume newline after P5
    fgets(line, sizeof(line), file); // consume generated-by comment

    if (fscanf(file, "%d %d", width, height) != 2) {
        fclose(file);
        return -2;
    }

    if (fscanf(file, "%d", &maxval) != 1 || maxval != PGM_MAXVAL) {
        fclose(file);
        return -2;
    }

    fgetc(file); // consume newline after 255

    size_t image_size = (size_t)(*width) * (size_t)(*height); // 1B per pixel
    *data = malloc(image_size);

    if (*data == NULL) {
        fclose(file);
        return -3;
    } // memory-allocation failure

    if (fread(*data, sizeof(uint8_t), image_size, file) != image_size) {
        free(*data);
        *data = NULL;
        fclose(file);
        return -4;
    } // incomplete read

    fclose(file);
    return 0;
}

int pgm_read_mpi(const char *filename, uint8_t **data, int *width, int *local_rows, int *height, int rank, int size)
{
    MPI_File file;
    MPI_Offset header_size = 0; // bytes from 0 to first pixel
    int maxval;

    if (rank == 0) { // only rank 0 reads pgm header
        FILE *header_file = fopen(filename, "rb");
        if (header_file == NULL) return -1;

        char magic[3];
        char line[256]; // temporary buffer

        if (fscanf(header_file, "%2s", magic) != 1 || strcmp(magic, "P5") != 0) {
            fclose(header_file);
            return -2;
        }

        fgetc(header_file);
        fgets(line, sizeof(line), header_file);

        if (fscanf(header_file, "%d %d", width, height) != 2) {
            fclose(header_file);
            return -2;
        }

        if (fscanf(header_file, "%d", &maxval) != 1 || maxval != PGM_MAXVAL) {
            fclose(header_file);
            return -2;
        }

        fgetc(header_file);
        header_size = ftell(header_file); // bytes from 0 to first pixel
        fclose(header_file);
    }

    // rank 0 broadcasts to other ranks
    MPI_Bcast(width, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(height, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(&header_size, 1, MPI_OFFSET, 0, MPI_COMM_WORLD);

    int base_rows = *height / size;
    int remainder = *height % size;
    *local_rows = base_rows + (rank < remainder);

    int start_row = rank * base_rows + (rank < remainder ? rank : remainder);
    MPI_Offset offset = header_size + (MPI_Offset)start_row * (*width);

    size_t image_size = (size_t)(*local_rows) * (size_t)(*width);
    *data = malloc(image_size);

    if (*data == NULL) {
        return -3;
    }

    // use MPI-IO on all ranks
    MPI_File_open(MPI_COMM_WORLD, filename, MPI_MODE_RDONLY, MPI_INFO_NULL, &file);
    MPI_File_read_at_all(file, offset, *data, (int)image_size, MPI_UNSIGNED_CHAR, MPI_STATUS_IGNORE);
    MPI_File_close(&file);

    return 0;
}

int pgm_write_mpi(const char *filename, const uint8_t *data, int width, int local_rows, int height, int rank, int size)
{
    MPI_File file;
    MPI_Offset header_size = 0; // bytes from 0 to first pixel

    int base_rows = height / size;
    int remainder = height % size;
    int start_row = rank * base_rows + (rank < remainder ? rank : remainder);

    if (rank == 0) { // only rank 0 writes the pgm header
        FILE *header_file = fopen(filename, "wb");
        if (header_file == NULL) return -1;

        fprintf(header_file, "P5\n# generated by gol\n%d %d\n%d\n",
                width, height, PGM_MAXVAL);

        header_size = ftell(header_file); // bytes from 0 to first pixel
        fclose(header_file);
    }

    // rank 0 broadcasts the header size to all ranks
    MPI_Bcast(&header_size, 1, MPI_OFFSET, 0, MPI_COMM_WORLD);

    // all ranks open the same file for parallel writing
    if (MPI_File_open(MPI_COMM_WORLD, filename, MPI_MODE_WRONLY | MPI_MODE_CREATE, MPI_INFO_NULL, &file) != MPI_SUCCESS)
        return -2;

    MPI_Offset offset = header_size + (MPI_Offset)start_row * width;
    size_t image_size = (size_t)local_rows * (size_t)width;

    // each rank writes its own rows directly to the correct file position
    if (MPI_File_write_at_all(file, offset, data, (int)image_size, MPI_UNSIGNED_CHAR, MPI_STATUS_IGNORE) != MPI_SUCCESS) {
        MPI_File_close(&file);
        return -3;
    }

    MPI_File_close(&file);
    return 0;
}