#include "pgm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>

#define PGM_MAXVAL 255
#define DEAD 0
#define ALIVE 1

int pgm_write(const char *filename, const uint8_t *data, int width, int height)
{
    FILE *file = fopen(filename, "wb");
    if (file == NULL) return -1;

    fprintf(file, "P5\n# generated by gol\n%d %d\n%d\n", width, height, PGM_MAXVAL);

    size_t image_size = (size_t)width * (size_t)height;
    uint8_t *pgm_data = malloc(image_size);

    if (pgm_data == NULL) {
        fclose(file);
        return -2;
    }

    for (size_t i = 0; i < image_size; i++)
        pgm_data[i] = data[i] == ALIVE ? PGM_MAXVAL : DEAD;

    if (fwrite(pgm_data, sizeof(uint8_t), image_size, file) != image_size) {
        free(pgm_data);
        fclose(file);
        return -3;
    }

    free(pgm_data);
    fclose(file);
    return 0;
}

int pgm_read(const char *filename, uint8_t **data, int *width, int *height)
{
    FILE *file = fopen(filename, "rb");
    if (file == NULL) return -1;

    char magic[3];
    int maxval;
    char line[256];

    if (fscanf(file, "%2s", magic) != 1 || strcmp(magic, "P5") != 0) {
        fclose(file);
        return -2;
    }

    fgetc(file);
    fgets(line, sizeof(line), file);

    if (fscanf(file, "%d %d", width, height) != 2) {
        fclose(file);
        return -2;
    }

    if (fscanf(file, "%d", &maxval) != 1 || maxval != PGM_MAXVAL) {
        fclose(file);
        return -2;
    }

    fgetc(file);

    size_t image_size = (size_t)(*width) * (size_t)(*height);
    uint8_t *pgm_data = malloc(image_size);

    if (pgm_data == NULL) {
        fclose(file);
        return -3;
    }

    if (fread(pgm_data, sizeof(uint8_t), image_size, file) != image_size) {
        free(pgm_data);
        fclose(file);
        return -4;
    }

    *data = malloc(image_size);

    if (*data == NULL) {
        free(pgm_data);
        fclose(file);
        return -3;
    }

    for (size_t i = 0; i < image_size; i++)
        (*data)[i] = pgm_data[i] == PGM_MAXVAL ? ALIVE : DEAD;

    free(pgm_data);
    fclose(file);
    return 0;
}

int pgm_read_mpi(const char *filename, uint8_t **data, int *width, int *local_rows, int *height, int rank, int size)
{
    MPI_File file;
    MPI_Offset header_size = 0;
    int maxval = 0;
    int header_result = 0;

    if (rank == 0) {
        FILE *header_file = fopen(filename, "rb");

        if (header_file == NULL) {
            header_result = -1;
        } else {
            char magic[3];
            char line[256];

            if (fscanf(header_file, "%2s", magic) != 1 || strcmp(magic, "P5") != 0) {
                header_result = -2;
            } else {
                fgetc(header_file);
                fgets(line, sizeof(line), header_file);

                if (fscanf(header_file, "%d %d", width, height) != 2) {
                    header_result = -2;
                } else if (fscanf(header_file, "%d", &maxval) != 1 || maxval != PGM_MAXVAL) {
                    header_result = -2;
                } else {
                    fgetc(header_file);
                    header_size = ftell(header_file);
                }
            }

            fclose(header_file);
        }
    }

    MPI_Bcast(&header_result, 1, MPI_INT, 0, MPI_COMM_WORLD);

    if (header_result != 0)
        return header_result;

    MPI_Bcast(width, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(height, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(&header_size, 1, MPI_OFFSET, 0, MPI_COMM_WORLD);

    int base_rows = *height / size;
    int remainder = *height % size;
    *local_rows = base_rows + (rank < remainder);

    int start_row = rank * base_rows + (rank < remainder ? rank : remainder);
    MPI_Offset offset = header_size + (MPI_Offset)start_row * (*width);

    size_t image_size = (size_t)(*local_rows) * (size_t)(*width);
    uint8_t *pgm_data = malloc(image_size);

    if (pgm_data == NULL)
        return -3;

    *data = malloc(image_size);

    if (*data == NULL) {
        free(pgm_data);
        return -3;
    }

    if (MPI_File_open(MPI_COMM_WORLD, filename, MPI_MODE_RDONLY, MPI_INFO_NULL, &file) != MPI_SUCCESS) {
        free(pgm_data);
        free(*data);
        *data = NULL;
        return -4;
    }

    int read_result = MPI_File_read_at_all(file, offset, pgm_data, (int)image_size, MPI_UNSIGNED_CHAR, MPI_STATUS_IGNORE);

    MPI_File_close(&file);

    if (read_result != MPI_SUCCESS) {
        free(pgm_data);
        free(*data);
        *data = NULL;
        return -5;
    }

    for (size_t i = 0; i < image_size; i++)
        (*data)[i] = pgm_data[i] == PGM_MAXVAL ? ALIVE : DEAD;

    free(pgm_data);
    return 0;
}

int pgm_write_mpi(const char *filename, const uint8_t *data, int width, int local_rows, int height, int rank, int size)
{
    MPI_File file;
    MPI_Offset header_size = 0;

    int base_rows = height / size;
    int remainder = height % size;
    int start_row = rank * base_rows + (rank < remainder ? rank : remainder);

    if (rank == 0) {
        FILE *header_file = fopen(filename, "wb");

        if (header_file == NULL)
            return -1;

        fprintf(header_file, "P5\n# generated by gol\n%d %d\n%d\n", width, height, PGM_MAXVAL);

        header_size = ftell(header_file);
        fclose(header_file);
    }

    MPI_Bcast(&header_size, 1, MPI_OFFSET, 0, MPI_COMM_WORLD);

    size_t image_size = (size_t)local_rows * (size_t)width;
    uint8_t *pgm_data = malloc(image_size);

    if (pgm_data == NULL)
        return -2;

    for (size_t i = 0; i < image_size; i++)
        pgm_data[i] = data[i] == ALIVE ? PGM_MAXVAL : DEAD;

    if (MPI_File_open(MPI_COMM_WORLD, filename, MPI_MODE_WRONLY | MPI_MODE_CREATE, MPI_INFO_NULL, &file) != MPI_SUCCESS) {
        free(pgm_data);
        return -3;
    }

    MPI_Offset offset = header_size + (MPI_Offset)start_row * width;

    int write_result = MPI_File_write_at_all(file, offset, pgm_data, (int)image_size, MPI_UNSIGNED_CHAR, MPI_STATUS_IGNORE);

    MPI_File_close(&file);
    free(pgm_data);

    if (write_result != MPI_SUCCESS)
        return -4;

    return 0;
}